# Generated by Django 5.2.8 on 2025-11-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_cash', models.FloatField()),
                ('income_pos', models.FloatField()),
                ('income_sum', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
